name: nisb_raw_material
description: 原料受入システム - NISB Raw Material Receiving System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.0.0
  provider: ^6.1.1
  http: ^1.2.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.0
  percent_indicator: ^4.2.3
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/